### ISSUE TITLE
invoke dubboStorageServiceImpl sql 'update STORAGE_TBL set count = count - 2 where commodity_code = 'C00321'' throws exceptin: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'context' in 'field list'

### ISSUE THREAD

**Issue by zhanggc** [fescar-group/seata-workshop#16]
invoke dubboStorageServiceImpl sql 'update STORAGE_TBL set count = count - 2 where commodity_code = 'C00321'' throws exceptin: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'context' in 'field list'

Exceptions:
2019-09-16 18:00:06.464 INFO [timeoutChecker_1]io.seata.core.rpc.netty.NettyPoolableFactory.makeObject:83 -register success, cost 4 ms, version:0.8.0,role:TMROLE,channel:[id: 0x7a8685e1, L:/192.168.17.105:50668 - R:/192.168.17.105:8102]
2019-09-16 18:00:21.034 INFO [DubboServerHandler-192.168.17.105:20882-thread-2]com.alibaba.fescar.workshop.service.StorageService.deduct:48 -Storage Service Begin ... xid: 192.168.17.105:8102:2022353747
2019-09-16 18:00:21.034 INFO [DubboServerHandler-192.168.17.105:20882-thread-2]com.alibaba.fescar.workshop.service.StorageService.deduct:49 -Deducting inventory SQL: update STORAGE_TBL set count = count - 2 where commodity_code = C00321
2019-09-16 18:00:21.108 INFO [DubboServerHandler-192.168.17.105:20882-thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:237 -load LoadBalance[null] extension by class[io.seata.discovery.loadbalance.RandomLoadBalance]
2019-09-16 18:00:21.233 WARN [DubboServerHandler-192.168.17.105:20882-thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:321 -io/protostuff/runtime/Delegate
2019-09-16 18:00:21.233 INFO [DubboServerHandler-192.168.17.105:20882-thread-2]io.seata.common.loader.EnhancedServiceLoader.loadFile:237 -load UndoLogParser[jackson] extension by class[io.seata.rm.datasource.undo.parser.JacksonUndoLogParser]
2019-09-16 18:00:21.315 ERROR[DubboServerHandler-192.168.17.105:20882-thread-2]io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue:104 -exception occur
java.sql.SQLException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'context' in 'field list'
	at io.seata.rm.datasource.ConnectionProxy.processGlobalTransactionCommit(ConnectionProxy.java:199)
	at io.seata.rm.datasource.ConnectionProxy.commit(ConnectionProxy.java:161)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:94)
	at io.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:57)
	at io.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:96)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:101)
	at io.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:47)
	at io.seata.rm.datasource.StatementProxy.executeUpdate(StatementProxy.java:76)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:511)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:508)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
	at com.alibaba.fescar.workshop.service.impl.StorageServiceImpl.deduct(StorageServiceImpl.java:52)
	at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at io.seata.integration.dubbo.TransactionPropagationFilter.invoke(TransactionPropagationFilter.java:60)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:48)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:96)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:148)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by slievrly** [comment]
@zhanggc https://github.com/seata/seata/tree/develop/script/client/at/db
